#!/usr/bin/env bash
# Script that will archive relevant logs generated by the server.

# Import your configuration
source config.sh

# Create a timestamp
TIMESTAMP=$(date +%Y%m%d%H%M%S)

# Backup filename with timestamp
BACKUP_FILE="sapiens_log_backup_$TIMESTAMP.tar.gz"

# Define full paths for tar operation
ENET_LOG_DIR=$(dirname "$ENET_LOG")
WORLD_LOGS_PARENT_DIR=$(dirname "$WORLD_LOGS_DIR")

# Archive the specific log file and the directory of log files
tar -czf "$BACKUP_FILE" -C "$ENET_LOG_DIR" "$(basename "$ENET_LOG")" -C "$WORLD_LOGS_PARENT_DIR" "$(basename "$WORLD_LOGS_DIR")"

# Move the archive to the log backup dir
mv "$BACKUP_FILE" $LOG_BACKUP_DIR

echo "Log Backup created: $BACKUP_FILE"
