#!/usr/bin/env bash

#---------------------------------------------------------------------------------------------
# WARNING! This file is generated by the install script to support the other scripts
# so you shouldn't change the values in here. Please run ./install.sh if you want to 
# change these values, select your existing world when found and fill in the values to change.
#---------------------------------------------------------------------------------------------

# Variables set up during installation.  
SCRIPT_DIR="/home/chillgenxer/sapiens-server"        # Base dir where the scripts are located.
WORLD_NAME="The Test World"        # The name of the world that people will see in-game
SERVER_ID="sapserver"          # The server dir name in the "players" dir
WORLD_ID="10a419425116ba47f9457bff145b30377a56ffb7"            # The unique world id that was generated
SCREEN_NAME="sapiens-server"    # Screen name for the server session.

# Network settings.  If exposing to the internet you will need to port forward all of these on your router.
UDP_PORT="5689"
#STEAM_PORT="5690" - Not configurable, listed for reference.  If you change the UDP_PORT this will be UDP_PORT + 1
HTTP_PORT="5700"
ADVERTISE=true
SERVER_NAME="ChillGenXer"      # Name of the server, as shown in Multiplayer Tab

# Server locations
GAME_DIR="/home/chillgenxer/.local/share/Steam/steamcmd/sapiens"        # Where Steam installs the linuxServer executable
SAPIENS_DIR="/home/chillgenxer/.local/share/majicjungle/sapiens"        # Location where linuxServer stores data
BACKUP_DIR="/home/chillgenxer/sapiens-server/world_backups"             # Folder where the backup command will send your world archive

# World Locations
WORLD_DIR="/home/chillgenxer/.local/share/majicjungle/sapiens/players/sapserver/worlds/10a419425116ba47f9457bff145b30377a56ffb7"
WORLD_CONFIG_LUA="/home/chillgenxer/.local/share/majicjungle/sapiens/players/sapserver/worlds/10a419425116ba47f9457bff145b30377a56ffb7/config.lua"
WORLD_INFO="/home/chillgenxer/.local/share/majicjungle/sapiens/players/sapserver/worlds/10a419425116ba47f9457bff145b30377a56ffb7/info.json"

# Logging
LOG_BACKUP_DIR="/home/chillgenxer/sapiens-server/log_backups"           # Folder where the logs will be archived.
ENET_LOG="/home/chillgenxer/.local/share/majicjungle/sapiens/enetServerLog.log"
SERVERLOG_LOG="/home/chillgenxer/.local/share/majicjungle/sapiens/players/sapserver/worlds/10a419425116ba47f9457bff145b30377a56ffb7/logs/serverLog.log"
WORLD_LOGS_DIR="/home/chillgenxer/.local/share/majicjungle/sapiens/players/sapserver/worlds/10a419425116ba47f9457bff145b30377a56ffb7/logs"
